### ISSUE TITLE
IPPPSSOOT of a file doesn't match its parent directory, cause errors at product label creation (no `trl` or `pdq` file for IPPPSSOOT from MAST to  store the timetags info inside `trl_timetags_by_ipppssoot` dictionary)

### ISSUE THREAD

**Issue by juzen2003** [SETI/rms-hst-pipeline#65]
- IPPPSSOOT of a file doesn't match its parent directory, for examples: 14903, 13197, 13874, these will have errors when creating labels. (`HST/product_labels/__init__.py`)
```
hst_14903/visit_a2/mastDownload/HST/odefa2010/odefa2hlj_epc.fits
hst_14903/visit_a2/mastDownload/HST/odefa2010/odefa2hmj_epc.fits
hst_14903/visit_a2/mastDownload/HST/odefa2010/odefa2hnj_epc.fits
hst_14903/visit_a2/mastDownload/HST/odefa2020/odefa2hlj_epc.fits
hst_14903/visit_a2/mastDownload/HST/odefa2020/odefa2hoj_epc.fits
hst_14903/visit_a2/mastDownload/HST/odefa2020/odefa2hpj_epc.fits
```
```
hst_13197/visit_03/mastDownload/HST/oc7e03020/oc7e03a1j_epc.fits
hst_13197/visit_03/mastDownload/HST/oc7e03020/oc7e03a2j_epc.fits
```
```
hst_13874/visit_02/mastDownload/HST/ocsk02020/ocsk02eqj_epc.fits
hst_13874/visit_02/mastDownload/HST/ocsk02020/ocsk02erj_epc.fits
```

**Comment by matthewtiscareno** [comment]
I imagine there should be metadata that tells us which of the two is actually the IPPPSSOOT.  Could you please send me some sample files?

**Comment by juzen2003** [comment]
Files are uploaded to dropbox under `Shared-pdart/bundles_from_hst_pipeline/files_from_mast`

**Comment by juzen2003** [comment]
Commands to reproduce the issue using files uploaded to the dropbox: (make sure to modify the path parameter to your own dropbox path)
```
- python pipeline/pipeline_label_hst_products.py --prog-id 15490 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_15490/visit_01'
- python pipeline/pipeline_label_hst_products.py --prog-id 14903 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_14903/visit_a2'
- python pipeline/pipeline_label_hst_products.py --prog-id 13197 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_13197/visit_03'
- python pipeline/pipeline_label_hst_products.py --prog-id 13874 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_13874/visit_02'
- python pipeline/pipeline_label_hst_products.py --prog-id 16770 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16770/visit_01'
- python pipeline/pipeline_label_hst_products.py --prog-id 16770 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16770/visit_02'
- python pipeline/pipeline_label_hst_products.py --prog-id 16770 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16770/visit_05'
- python pipeline/pipeline_label_hst_products.py --prog-id 16770 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16770/visit_06'
- python pipeline/pipeline_label_hst_products.py --prog-id 12607 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_12607/visit_20'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_01'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_02'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_03'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_04'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_05'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_06'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_07'
- python pipeline/pipeline_label_hst_products.py --prog-id 16704 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_16704/visit_08'
- python pipeline/pipeline_label_hst_products.py --prog-id 12478 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_12478/visit_a1'
- python pipeline/pipeline_label_hst_products.py --prog-id 12478 --path '/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-pdart/bundles_from_hst_pipeline/files_from_mast/hst_12478/visit_a2'
```

**Comment by juzen2003** [comment]
- Use `15490` as an example. (all files are downloaded from MAST and uploaded to Dropbox)
- This is the traceback when error happened
```
Traceback (most recent call last):
  File "/Users/yu-jenchang/Desktop/seti/workspace/pds-hst-pipeline/HST/pipeline/pipeline_label_hst_products.py", line 124, in <module>
    label_hst_fits_directories(target_path,
  File "/Users/yu-jenchang/Desktop/seti/workspace/pds-hst-pipeline/HST/product_labels/__init__.py", line 82, in label_hst_fits_directories
    label_hst_fits_filepaths(filepaths, root,
  File "/Users/yu-jenchang/Desktop/seti/workspace/pds-hst-pipeline/HST/product_labels/__init__.py", line 488, in label_hst_fits_filepaths
    ipppssoot_dict['timetags'] = trl_timetags_by_ipppssoot[ipppssoot]
KeyError: 'odtf01dqj'
```
The `ipppssoot` here is `odtf01dqj` but it doesn't exists in `trl_timetags_by_ipppssoot`, the key of `trl_timetags_by_ipppssoot` are `ipppssoot` of all parents folders: 
```
odtf01010
odtf01020
odtf01030
odtf01040
odtf01050
odtf01060
odtf01070
odtf01080
odtf01090
odtf010a0
odtf010b0
odtf010c0
odtf010d0
odtf010e0
odtf010f0
odtf01dpq
```
Here is the value of `trl_timetags_by_ipppssoot`:
```
{'odtf01010': {'2023-07-28': '2023-07-28T19:12:21', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:34:17'}, 'odtf01020': {'2023-07-28': '2023-07-28T19:26:41', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:42:00'}, 'odtf01030': {'2023-07-28': '2023-07-28T19:12:38', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:34:53'}, 'odtf01040': {'2023-07-28': '2023-07-28T19:12:23', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:34:15'}, 'odtf01050': {'2023-07-28': '2023-07-28T19:12:31', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:34:54'}, 'odtf01060': {'2023-07-28': '2023-07-28T19:12:23', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:34:14'}, 'odtf01070': {'2023-07-28': '2023-07-28T19:12:41', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:53'}, 'odtf01080': {'2023-07-28': '2023-07-28T19:12:22', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:49'}, 'odtf01090': {'2023-07-28': '2023-07-28T19:12:24', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:55'}, 'odtf010a0': {'2023-07-28': '2023-07-28T19:12:21', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:51'}, 'odtf010b0': {'2023-07-28': '2023-07-28T19:12:22', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:50'}, 'odtf010c0': {'2023-07-28': '2023-07-28T19:12:24', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:51'}, 'odtf010d0': {'2023-07-28': '2023-07-28T19:12:23', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:53'}, 'odtf010e0': {'2023-07-28': '2023-07-28T19:12:24', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:49'}, 'odtf010f0': {'2023-07-28': '2023-07-28T19:12:24', '2019-08-10': '2019-08-10T23:35:43', '2023-08-01': '2023-08-01T02:37:53'}, 'odtf01dpq': {'2019-08-10': '2019-08-10T23:35:42', '2023-07-28': '2023-07-28T19:12:33', '2023-08-01': '2023-08-01T02:37:58'}}
```

**Comment by juzen2003** [comment]
Use `15490` as an example. When adding an ipppssoot as a key to `trl_timetags_by_ipppssoot` dictionary, we are expecting to get those info from files with suffix `trl` or `pdq` (line 288-295 in `product_labels/__init__.py`). But for the case like `odtf01dqj`, it has only one transmission character and it's under `hst_15490/visit_01/mastDownload/HST/odtf01010/odtf01dqj_epc.fits`. There is no `trl` or `pdq` file for this ipppssoot (not existing on MAST). Here is the list of files (not filtered by accepted suffix or accepted instrument code) that we can download from MAST, and there is only `odtf01dqj_epc.fits` exists for this ipppssoot:
```
odtf01dqj_epc.fits
odtf01e5j_epc.fits
odtf01010_jif.fits
odtf01010_jit.fits
odtf01010_jwf.fits
odtf01010_jwt.fits
odtf01010_spt.fits
odtf01010_trl.fits
odtf01010_wav.fits
odtf01010_wsp.fits
odtf01010_asn.fits
odtf01010_log.txt
odtf01010_x1d.png
odtf01010_raw.fits
odtf01010_x1d.fits
odtf01010_x2d.fits
odtf01010_flt.fits
odtf01drj_epc.fits
odtf01e5j_epc.fits
odtf01020_jif.fits
odtf01020_jit.fits
odtf01020_jwf.fits
odtf01020_jwt.fits
odtf01020_spt.fits
odtf01020_trl.fits
odtf01020_wav.fits
odtf01020_wsp.fits
odtf01020_asn.fits
odtf01020_log.txt
odtf01020_x1d.png
odtf01020_raw.fits
odtf01020_x1d.fits
odtf01020_x2d.fits
odtf01020_flt.fits
odtf01dsj_epc.fits
odtf01e5j_epc.fits
odtf01030_jif.fits
odtf01030_jit.fits
odtf01030_jwf.fits
odtf01030_jwt.fits
odtf01030_spt.fits
odtf01030_trl.fits
odtf01030_wav.fits
odtf01030_wsp.fits
odtf01030_asn.fits
odtf01030_log.txt
odtf01030_x1d.png
odtf01030_raw.fits
odtf01030_x1d.fits
odtf01030_x2d.fits
odtf01030_flt.fits
odtf01dtj_epc.fits
odtf01e5j_epc.fits
odtf01040_jif.fits
odtf01040_jit.fits
odtf01040_jwf.fits
odtf01040_jwt.fits
odtf01040_spt.fits
odtf01040_trl.fits
odtf01040_wav.fits
odtf01040_wsp.fits
odtf01040_asn.fits
odtf01040_log.txt
odtf01040_x1d.png
odtf01040_raw.fits
odtf01040_x1d.fits
odtf01040_x2d.fits
odtf01040_flt.fits
odtf01duj_epc.fits
odtf01e5j_epc.fits
odtf01050_jif.fits
odtf01050_jit.fits
odtf01050_jwf.fits
odtf01050_jwt.fits
odtf01050_spt.fits
odtf01050_trl.fits
odtf01050_wav.fits
odtf01050_wsp.fits
odtf01050_asn.fits
odtf01050_log.txt
odtf01050_x1d.png
odtf01050_raw.fits
odtf01050_x1d.fits
odtf01050_x2d.fits
odtf01050_flt.fits
odtf01dvj_epc.fits
odtf01e5j_epc.fits
odtf01060_jif.fits
odtf01060_jit.fits
odtf01060_jwf.fits
odtf01060_jwt.fits
odtf01060_spt.fits
odtf01060_trl.fits
odtf01060_wav.fits
odtf01060_wsp.fits
odtf01060_asn.fits
odtf01060_log.txt
odtf01060_x1d.png
odtf01060_raw.fits
odtf01060_x1d.fits
odtf01060_x2d.fits
odtf01060_flt.fits
odtf01dwj_epc.fits
odtf01e5j_epc.fits
odtf01070_jif.fits
odtf01070_jit.fits
odtf01070_jwf.fits
odtf01070_jwt.fits
odtf01070_spt.fits
odtf01070_trl.fits
odtf01070_wav.fits
odtf01070_wsp.fits
odtf01070_asn.fits
odtf01070_log.txt
odtf01070_x1d.png
odtf01070_raw.fits
odtf01070_x1d.fits
odtf01070_x2d.fits
odtf01070_flt.fits
odtf01dxj_epc.fits
odtf01e5j_epc.fits
odtf01080_jif.fits
odtf01080_jit.fits
odtf01080_jwf.fits
odtf01080_jwt.fits
odtf01080_spt.fits
odtf01080_trl.fits
odtf01080_wav.fits
odtf01080_wsp.fits
odtf01080_asn.fits
odtf01080_log.txt
odtf01080_x1d.png
odtf01080_raw.fits
odtf01080_x1d.fits
odtf01080_x2d.fits
odtf01080_flt.fits
odtf01dyj_epc.fits
odtf01e5j_epc.fits
odtf01090_jif.fits
odtf01090_jit.fits
odtf01090_jwf.fits
odtf01090_jwt.fits
odtf01090_spt.fits
odtf01090_trl.fits
odtf01090_wav.fits
odtf01090_wsp.fits
odtf01090_asn.fits
odtf01090_log.txt
odtf01090_x1d.png
odtf01090_raw.fits
odtf01090_x1d.fits
odtf01090_x2d.fits
odtf01090_flt.fits
odtf01dzj_epc.fits
odtf01e5j_epc.fits
odtf010a0_jif.fits
odtf010a0_jit.fits
odtf010a0_jwf.fits
odtf010a0_jwt.fits
odtf010a0_spt.fits
odtf010a0_trl.fits
odtf010a0_wav.fits
odtf010a0_wsp.fits
odtf010a0_asn.fits
odtf010a0_log.txt
odtf010a0_x1d.png
odtf010a0_raw.fits
odtf010a0_x1d.fits
odtf010a0_x2d.fits
odtf010a0_flt.fits
odtf01e0j_epc.fits
odtf01e5j_epc.fits
odtf010b0_jif.fits
odtf010b0_jit.fits
odtf010b0_jwf.fits
odtf010b0_jwt.fits
odtf010b0_spt.fits
odtf010b0_trl.fits
odtf010b0_wav.fits
odtf010b0_wsp.fits
odtf010b0_asn.fits
odtf010b0_log.txt
odtf010b0_x1d.png
odtf010b0_raw.fits
odtf010b0_x1d.fits
odtf010b0_x2d.fits
odtf010b0_flt.fits
odtf01e1j_epc.fits
odtf01e5j_epc.fits
odtf010c0_jif.fits
odtf010c0_jit.fits
odtf010c0_jwf.fits
odtf010c0_jwt.fits
odtf010c0_spt.fits
odtf010c0_trl.fits
odtf010c0_wav.fits
odtf010c0_wsp.fits
odtf010c0_asn.fits
odtf010c0_log.txt
odtf010c0_x1d.png
odtf010c0_raw.fits
odtf010c0_x1d.fits
odtf010c0_x2d.fits
odtf010c0_flt.fits
odtf01e2j_epc.fits
odtf01e5j_epc.fits
odtf010d0_jif.fits
odtf010d0_jit.fits
odtf010d0_jwf.fits
odtf010d0_jwt.fits
odtf010d0_spt.fits
odtf010d0_trl.fits
odtf010d0_wav.fits
odtf010d0_wsp.fits
odtf010d0_asn.fits
odtf010d0_log.txt
odtf010d0_x1d.png
odtf010d0_raw.fits
odtf010d0_x1d.fits
odtf010d0_x2d.fits
odtf010d0_flt.fits
odtf01e3j_epc.fits
odtf01e5j_epc.fits
odtf010e0_jif.fits
odtf010e0_jit.fits
odtf010e0_jwf.fits
odtf010e0_jwt.fits
odtf010e0_spt.fits
odtf010e0_trl.fits
odtf010e0_wav.fits
odtf010e0_wsp.fits
odtf010e0_asn.fits
odtf010e0_log.txt
odtf010e0_x1d.png
odtf010e0_raw.fits
odtf010e0_x1d.fits
odtf010e0_x2d.fits
odtf010e0_flt.fits
odtf01e4j_epc.fits
odtf01e5j_epc.fits
odtf010f0_jif.fits
odtf010f0_jit.fits
odtf010f0_jwf.fits
odtf010f0_jwt.fits
odtf010f0_spt.fits
odtf010f0_trl.fits
odtf010f0_wav.fits
odtf010f0_wsp.fits
odtf010f0_asn.fits
odtf010f0_log.txt
odtf010f0_x1d.png
odtf010f0_raw.fits
odtf010f0_x1d.fits
odtf010f0_x2d.fits
odtf010f0_flt.fits
odtf01dpj_epc.fits
odtf01dpj_jif.fits
odtf01dpj_jit.fits
odtf01dpq_spt.fits
odtf01dpq_trl.fits
odtf01dpq_log.txt
odtf01dpq_raw.fits
```
And if we looked at the `asn` file from the parent `ipppssoot`, we should be expecting `trl` file from `odtf01dqq` (something similar to the case like `odtf01dpq`), but as you can see from the above list, there is no such file from MAST. So my question is: is this another case where we are missing files from MAST and need to decide how we should handle it?
```
In [31]: h = pyfits.open('/Users/yu-jenchang/tmp-working-dir/HST_STAGING/hst_15490/visit_01/mastDownload/HST/odtf01010/odtf
    ...: 01010_asn.fits')

In [32]: print(h[1].data)
[('ODTF01DQQ', 'SCIENCE',  1) ('ODTF01E5Q', 'GO-WAVECAL',  1)
 ('ODTF01010', 'PRODUCT',  1)]

In [33]: 
```

**Comment by matthewtiscareno** [comment]
@markshowalter is addressing this.  A pull request should be forthcoming.

**Comment by matthewtiscareno** [comment]
This issue was fixed by #102.
